name: API tests

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
  
    # SQLite3 is available on Ubuntu runner by default

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.3'
        bundler-cache: true
    
    - name: Install Rails dependencies
      run: |
        cd thanx_api
        bundle install
    
    - name: Setup database
      run: |
        cd thanx_api
        bundle exec rails db:create
        bundle exec rails db:schema:load
    
    - name: Run RuboCop
      run: |
        cd thanx_api
        bundle exec rubocop --parallel
    
    - name: Run RSpec
      run: |
        cd thanx_api
        bundle exec rspec --format documentation 